context:
  name: pyrefly
  version: "0.16.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: d4b2f24b7099fe6ed1f778c7ac45019ea59e64949280647dde5309d7c2a20599

build:
  script: |
    set -euxo pipefail
    cd pyrefly && cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    cd .. && python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - make
  host:
    - python
    - pip
    - setuptools
    - maturin >=1.0,<2.0
  run:
    - python

tests:
  - python:
      imports:
      - pyrefly
      pip_check: true

about:
  homepage: https://github.com/facebook/pyrefly
  summary: A faster Python type checker written in Rust
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - apmorton
